apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c12krdfow-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1588e9c811.2ctv.p3.openshiftapps.com/rhtap/rhtap-qe:9e5a6edce9c037bdbba4277de2c40aec73db3a30@sha256:87a755de8c4ed45ee61602ccf001c73ecc512e897e212a4503472219f45e72ca
          name: container-image
